# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Study/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/design_1_gtwizard_ultrascale_0_0.xci
# IP: The module: 'design_1_gtwizard_ultrascale_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0 || ORIG_REF_NAME==gtwizard_ultrascale_0} -quiet] -quiet

# IP: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0_vio_0 || ORIG_REF_NAME==gtwizard_ultrascale_0_vio_0} -quiet] -quiet

# XDC: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc

# XDC: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0 || ORIG_REF_NAME==gtwizard_ultrascale_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0_vio_0 || ORIG_REF_NAME==gtwizard_ultrascale_0_vio_0} -quiet] -quiet

# XDC: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0_example_top.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_gtwizard_ultrascale_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Study/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/design_1_gtwizard_ultrascale_0_0.xci
# IP: The module: 'design_1_gtwizard_ultrascale_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0 || ORIG_REF_NAME==gtwizard_ultrascale_0} -quiet] -quiet

# IP: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0_vio_0 || ORIG_REF_NAME==gtwizard_ultrascale_0_vio_0} -quiet] -quiet

# XDC: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc

# XDC: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0 || ORIG_REF_NAME==gtwizard_ultrascale_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0_vio_0 || ORIG_REF_NAME==gtwizard_ultrascale_0_vio_0} -quiet] -quiet

# XDC: e:/Study/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_gtwizard_ultrascale_0_0/src/gtwizard_ultrascale_0_example_top.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_gtwizard_ultrascale_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
